"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IbanVisibility = exports.VatPriceMode = exports.InvoiceFireEvent = exports.ExpenseFireEvent = exports.VatMode = void 0;
var VatMode;
(function (VatMode) {
    VatMode["vat_payer"] = "vat_payer";
    VatMode["non_vat_payer"] = "non_vat_payer";
    VatMode["identified_person"] = "identified_person";
})(VatMode = exports.VatMode || (exports.VatMode = {}));
var ExpenseFireEvent;
(function (ExpenseFireEvent) {
    ExpenseFireEvent["pay"] = "pay";
    ExpenseFireEvent["remove_payment"] = "remove_payment";
    ExpenseFireEvent["lock"] = "lock";
    ExpenseFireEvent["unlock"] = "unlock";
})(ExpenseFireEvent = exports.ExpenseFireEvent || (exports.ExpenseFireEvent = {}));
var InvoiceFireEvent;
(function (InvoiceFireEvent) {
    InvoiceFireEvent["mark_as_sent"] = "mark_as_sent";
    InvoiceFireEvent["deliver"] = "deliver";
    InvoiceFireEvent["pay"] = "pay";
    InvoiceFireEvent["pay_proforma"] = "pay_proforma";
    InvoiceFireEvent["pay_partial_proforma"] = "pay_partial_proforma";
    InvoiceFireEvent["remove_payment"] = "remove_payment";
    InvoiceFireEvent["deliver_reminder"] = "deliver_reminder";
    InvoiceFireEvent["cancel"] = "cancel";
    InvoiceFireEvent["undo_cancel"] = "undo_cancel";
    InvoiceFireEvent["lock"] = "lock";
    InvoiceFireEvent["unlock"] = "unlock";
    InvoiceFireEvent["mark_as_uncollectible"] = "mark_as_uncollectible";
    InvoiceFireEvent["undo_uncollectible"] = "undo_uncollectible";
})(InvoiceFireEvent = exports.InvoiceFireEvent || (exports.InvoiceFireEvent = {}));
var VatPriceMode;
(function (VatPriceMode) {
    VatPriceMode[VatPriceMode["without_vat"] = 0] = "without_vat";
    VatPriceMode[VatPriceMode["from_total_with_vat"] = 1] = "from_total_with_vat";
})(VatPriceMode = exports.VatPriceMode || (exports.VatPriceMode = {}));
var TodoName;
(function (TodoName) {
    TodoName["initial"] = "initial";
    TodoName["initial_fb"] = "initial_fb";
    TodoName["email_bounced"] = "email_bounced";
    TodoName["email_for_subject_bounced"] = "email_for_subject_bounced";
    TodoName["invoice_overdue"] = "invoice_overdue";
    TodoName["invoice_partial_proforma_paid"] = "invoice_partial_proforma_paid";
    TodoName["invoice_partial_proforma_paid_bank"] = "invoice_partial_proforma_paid_bank";
    TodoName["invoice_partial_proforma_paid_paypal"] = "invoice_partial_proforma_paid_paypal";
    TodoName["invoice_partial_proforma_paid_gopay"] = "invoice_partial_proforma_paid_gopay";
    TodoName["invoice_already_paid"] = "invoice_already_paid";
    TodoName["expense_already_paid"] = "expense_already_paid";
    TodoName["unpaired_payment"] = "unpaired_payment";
    TodoName["invoice_payment_unpaired"] = "invoice_payment_unpaired";
    TodoName["expense_payment_unpaired"] = "expense_payment_unpaired";
    TodoName["bank_email_received_but_pairing_disabled"] = "bank_email_received_but_pairing_disabled";
    TodoName["subject_unreliable_vat_payer"] = "subject_unreliable_vat_payer";
    TodoName["subject_reliable_vat_payer"] = "subject_reliable_vat_payer";
    TodoName["generator_finished"] = "generator_finished";
    TodoName["generator_failed"] = "generator_failed";
    TodoName["webhook_failed"] = "webhook_failed";
    TodoName["paypal_unverified_notification"] = "paypal_unverified_notification";
    TodoName["paypal_tampered_payment"] = "paypal_tampered_payment";
    TodoName["paypal_uncompleted_payment"] = "paypal_uncompleted_payment";
    TodoName["paypal_invalid_token"] = "paypal_invalid_token";
    TodoName["gopay_invalid_token"] = "gopay_invalid_token";
    TodoName["gopay_unpaired_payment"] = "gopay_unpaired_payment";
    TodoName["gopay_uncompleted_payment"] = "gopay_uncompleted_payment";
    TodoName["gopay_wrong_credentials"] = "gopay_wrong_credentials";
    TodoName["suspicious_account"] = "suspicious_account";
    TodoName["account_near_vat_turnover_limit"] = "account_near_vat_turnover_limit";
    TodoName["account_exceeded_vat_turnover_limit"] = "account_exceeded_vat_turnover_limit";
})(TodoName || (TodoName = {}));
var IbanVisibility;
(function (IbanVisibility) {
    IbanVisibility[IbanVisibility["automatically"] = 0] = "automatically";
    IbanVisibility[IbanVisibility["always"] = 1] = "always";
})(IbanVisibility = exports.IbanVisibility || (exports.IbanVisibility = {}));
